/* Generated by Astilba Env. Do not edit. */
import {
  checkProcessTargetWithSchemas,
  loadProcessTargetWithSchemas,
  type ProcessSource,
  type ProcessTargetDefinition,
  type StandardSchemaV1,
} from "@astilba/env/runtime";

export interface Configuration {
  readonly "analyticsId"?: string;
  readonly "apiOrigin": string;
  readonly "appName"?: string;
  readonly "applicationOrigin": string;
  readonly "configText"?: string;
  readonly "databaseUrl": string;
  readonly "debug": boolean;
  readonly "features": readonly string[];
  readonly "maxConnections": number;
  readonly "port": number;
  readonly "secretKey"?: string;
}

type __AstilbaExpectedSchemaPairs = Readonly<{
  readonly "databaseUrl": readonly [string, string];
}>;
type __AstilbaSchemaCandidates = Readonly<{
  readonly [TName in keyof __AstilbaExpectedSchemaPairs]: StandardSchemaV1;
}>;
type __AstilbaSchemaTypes<TSchema extends StandardSchemaV1> =
  TSchema["~standard"] extends { readonly types?: infer TTypes }
    ? NonNullable<TTypes>
    : never;
type __AstilbaSchemaInput<TSchema extends StandardSchemaV1> =
  __AstilbaSchemaTypes<TSchema> extends { readonly input: infer TInput }
    ? TInput
    : never;
type __AstilbaSchemaOutput<TSchema extends StandardSchemaV1> =
  __AstilbaSchemaTypes<TSchema> extends { readonly output: infer TOutput }
    ? TOutput
    : never;
type __AstilbaIsExactly<TLeft, TRight> =
  (<TValue>() => TValue extends TLeft ? 1 : 2) extends
  (<TValue>() => TValue extends TRight ? 1 : 2)
    ? (<TValue>() => TValue extends TRight ? 1 : 2) extends
      (<TValue>() => TValue extends TLeft ? 1 : 2)
      ? true
      : false
    : false;
type __AstilbaSchemaChecks<TSchemas extends __AstilbaSchemaCandidates> = {
  readonly [TName in keyof __AstilbaExpectedSchemaPairs]:
    __AstilbaIsExactly<
      __AstilbaSchemaInput<TSchemas[TName]>,
      __AstilbaExpectedSchemaPairs[TName][0]
    > extends true
      ? __AstilbaIsExactly<
          __AstilbaSchemaOutput<TSchemas[TName]>,
          __AstilbaExpectedSchemaPairs[TName][1]
        >
      : false;
}[keyof __AstilbaExpectedSchemaPairs];
type __AstilbaSchemaGate<TSchemas extends __AstilbaSchemaCandidates> =
  Exclude<keyof TSchemas, keyof __AstilbaSchemaCandidates> extends never
    ? __AstilbaSchemaChecks<TSchemas> extends true
      ? unknown
      : { readonly __astilbaSchemaTypeMismatch: never }
    : { readonly __astilbaSchemaMapMismatch: never };
export type Schemas<TSchemas extends __AstilbaSchemaCandidates> =
  TSchemas & __AstilbaSchemaGate<TSchemas>;

const definition = (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "bindings", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "analyticsId" });
  Object.defineProperty(output, "source", { enumerable: true, value: "ANALYTICS_ID" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "apiOrigin" });
  Object.defineProperty(output, "source", { enumerable: true, value: "API_URL" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "appName" });
  Object.defineProperty(output, "source", { enumerable: true, value: "APP_NAME" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "applicationOrigin" });
  Object.defineProperty(output, "source", { enumerable: true, value: "APPLICATION_ORIGIN" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "configText" });
  Object.defineProperty(output, "source", { enumerable: true, value: "CONFIG" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "databaseUrl" });
  Object.defineProperty(output, "source", { enumerable: true, value: "DATABASE_URL" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "debug" });
  Object.defineProperty(output, "source", { enumerable: true, value: "DEBUG" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "features" });
  Object.defineProperty(output, "source", { enumerable: true, value: "FEATURES" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "maxConnections" });
  Object.defineProperty(output, "source", { enumerable: true, value: "MAX_CONNECTIONS" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "port" });
  Object.defineProperty(output, "source", { enumerable: true, value: "APPLICATION_PORT" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "secretKey" });
  Object.defineProperty(output, "source", { enumerable: true, value: "SECRET_KEY" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "generated", { enumerable: true, value: "astilba.env.generated-module/v1" });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "projection", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "canonicalisation", { enumerable: true, value: "astilba.jcs/v1" });
  Object.defineProperty(output, "codecAbi", { enumerable: true, value: "astilba.env.codec/v1" });
  Object.defineProperty(output, "consumer", { enumerable: true, value: "server" });
  Object.defineProperty(output, "contract", { enumerable: true, value: "com.astilba.example.app-router" });
  Object.defineProperty(output, "entries", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.string-code-point/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "string" });
  Object.defineProperty(output, "maxCodePoints", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minCodePoints", { enumerable: true, value: 1 });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","analyticsId"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "analyticsId" });
  Object.defineProperty(output, "required", { enumerable: true, value: false });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.origin-ascii/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "origin" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","apiOrigin"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "apiOrigin" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.string-code-point/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "string" });
  Object.defineProperty(output, "maxCodePoints", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minCodePoints", { enumerable: true, value: 1 });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","appName"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "appName" });
  Object.defineProperty(output, "required", { enumerable: true, value: false });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.origin-ascii/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "origin" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","applicationOrigin"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "applicationOrigin" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.text/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "missing" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "text" });
  Object.defineProperty(output, "maxCodePoints", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minCodePoints", { enumerable: true, value: 1 });
  Object.defineProperty(output, "normalise", { enumerable: true, value: "preserve" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","configText"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "configText" });
  Object.defineProperty(output, "required", { enumerable: true, value: false });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "private" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.opaque/v1" });
  Object.defineProperty(output, "input", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "kind", { enumerable: true, value: "string" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "kind", { enumerable: true, value: "opaque" });
  Object.defineProperty(output, "output", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "kind", { enumerable: true, value: "string" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "revision", { enumerable: true, value: "1" });
  Object.defineProperty(output, "semantics", { enumerable: true, value: "com.astilba.example.database-url/v1" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","databaseUrl"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "databaseUrl" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "private" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.boolean-exact/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "invalid" });
  Object.defineProperty(output, "falseInput", { enumerable: true, value: "false" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "boolean" });
  Object.defineProperty(output, "trueInput", { enumerable: true, value: "true" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","debug"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "debug" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.string-list-comma/v1" });
  Object.defineProperty(output, "emptyItems", { enumerable: true, value: "drop" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "string-list" });
  Object.defineProperty(output, "maximumItemCodePoints", { enumerable: true, value: 1024 });
  Object.defineProperty(output, "maximumItems", { enumerable: true, value: 64 });
  Object.defineProperty(output, "minimumItemCodePoints", { enumerable: true, value: 1 });
  Object.defineProperty(output, "minimumItems", { enumerable: true, value: 0 });
  Object.defineProperty(output, "separator", { enumerable: true, value: "," });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","features"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "features" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.integer/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "missing" });
  Object.defineProperty(output, "default", { enumerable: true, value: null });
  Object.defineProperty(output, "kind", { enumerable: true, value: "integer" });
  Object.defineProperty(output, "maximum", { enumerable: true, value: 10000 });
  Object.defineProperty(output, "minimum", { enumerable: true, value: 1 });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","maxConnections"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "maxConnections" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "private" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.safe-integer-decimal/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "missing" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "safe-integer" });
  Object.defineProperty(output, "maximum", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minimum", { enumerable: true, value: 1 });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","port"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "port" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.text/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "missing" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "text" });
  Object.defineProperty(output, "maxCodePoints", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minCodePoints", { enumerable: true, value: 1 });
  Object.defineProperty(output, "normalise", { enumerable: true, value: "preserve" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.app-router","secretKey"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "secretKey" });
  Object.defineProperty(output, "required", { enumerable: true, value: false });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "private" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "format", { enumerable: true, value: "astilba.env.projection" });
  Object.defineProperty(output, "formatVersion", { enumerable: true, value: 1 });
  Object.defineProperty(output, "kind", { enumerable: true, value: "server" });
  Object.defineProperty(output, "projectionAbi", { enumerable: true, value: "astilba.env.projection/v1" });
  return Object.freeze(output);
})() });
  return Object.freeze(output);
})() as ProcessTargetDefinition;

export const check = <const TSchemas extends __AstilbaSchemaCandidates>(
  source: ProcessSource,
  schemas: Schemas<TSchemas>,
) => checkProcessTargetWithSchemas<Configuration>(definition, source, schemas);

export const load = <const TSchemas extends __AstilbaSchemaCandidates>(
  source: ProcessSource,
  schemas: Schemas<TSchemas>,
): Promise<Configuration> =>
  loadProcessTargetWithSchemas<Configuration>(definition, source, schemas);
