/* Generated by Astilba Env. Do not edit. */
import type { BrowserProjection } from "@astilba/env/browser";

export interface Configuration {
  readonly "apiOrigin": string;
  readonly "appName": string;
  readonly "applicationOrigin": string;
  readonly "debug": boolean;
  readonly "features": readonly string[];
  readonly "port": number;
}

const validText = (value: unknown, minimum: number, maximum: number): value is string => {
  if (typeof value !== "string" || value.length > maximum * 2) {
    return false;
  }
  const length = [...value].length;
  return length >= minimum && length <= maximum;
};

const normaliseOrigin = (input: unknown): string | undefined => {
  if (typeof input !== "string") {
    return undefined;
  }
  for (let index = 0; index < input.length; index += 1) {
    const code = input.codePointAt(index);
    if (code === undefined || code > 0x7f) {
      return undefined;
    }
  }
  if (!input.startsWith("https://")) {
    return undefined;
  }
  let authority = input.slice(8);
  if (authority.endsWith("/")) {
    authority = authority.slice(0, -1);
  }
  if (
    authority.length === 0 ||
    authority.includes("/") ||
    authority.includes("?") ||
    authority.includes("#") ||
    authority.includes("@")
  ) {
    return undefined;
  }
  const colon = authority.indexOf(":");
  if (colon !== authority.lastIndexOf(":")) {
    return undefined;
  }
  const host = colon < 0 ? authority : authority.slice(0, colon);
  const port = colon < 0 ? undefined : authority.slice(colon + 1);
  if (
    host.length === 0 ||
    host.length > 253 ||
    host.endsWith(".") ||
    host === "localhost"
  ) {
    return undefined;
  }
  const labels = host.split(".");
  if (
    labels.length < 2 ||
    /^(?:(?:0x[\da-f]+|\d+)\.){1,3}0x[\da-f]+$/u.test(host) ||
    !/[a-z][a-z0-9-]*$/u.test(host) ||
    labels.some((label) =>
      label.length === 0 ||
      label.length > 63 ||
      !/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/u.test(label),
    ) ||
    (port !== undefined &&
      (!/^[1-9][0-9]*$/u.test(port) ||
        port.length > 5 ||
        Number(port) > 65_535))
  ) {
    return undefined;
  }
  return `https://${host}${port === undefined || port === "443" ? "" : `:${port}`}`;
};

const decode = (
  input: Readonly<Record<string, unknown>>,
  failure: (
    code: "BOOTSTRAP_UNKNOWN_FIELD" | "BOOTSTRAP_VALUE_INVALID" | "BOOTSTRAP_VALUE_MISSING",
  ) => never,
): Readonly<Configuration> => {
  const selected = new Set(Object.freeze(["apiOrigin","appName","applicationOrigin","debug","features","port"]));
  if (Reflect.ownKeys(input).some((key) => typeof key !== "string" || !selected.has(key))) {
    failure("BOOTSTRAP_UNKNOWN_FIELD");
  }
  const invalid = (): never => failure("BOOTSTRAP_VALUE_INVALID");
  const missing = (): never => failure("BOOTSTRAP_VALUE_MISSING");
  const values = Object.create(null) as Record<string, unknown>;

  if (!Object.hasOwn(input, "apiOrigin")) {
    missing();
  }
  const raw0 = input["apiOrigin"];
  const value0 = normaliseOrigin(raw0);
  if (value0 === undefined) {
    invalid();
  }
  Object.defineProperty(values, "apiOrigin", { enumerable: true, value: value0 });

  if (!Object.hasOwn(input, "appName")) {
    missing();
  }
  const raw1 = input["appName"];
  if (!validText(raw1, 1, 65535)) {
    invalid();
  }
  const value1 = raw1;
  Object.defineProperty(values, "appName", { enumerable: true, value: value1 });

  if (!Object.hasOwn(input, "applicationOrigin")) {
    missing();
  }
  const raw2 = input["applicationOrigin"];
  const value2 = normaliseOrigin(raw2);
  if (value2 === undefined) {
    invalid();
  }
  Object.defineProperty(values, "applicationOrigin", { enumerable: true, value: value2 });

  if (!Object.hasOwn(input, "debug")) {
    missing();
  }
  const raw3 = input["debug"];
  if (typeof raw3 !== "boolean") {
    invalid();
  }
  const value3 = raw3;
  Object.defineProperty(values, "debug", { enumerable: true, value: value3 });

  if (!Object.hasOwn(input, "features")) {
    missing();
  }
  const raw4 = input["features"];
  if (!Array.isArray(raw4)) {
    return invalid();
  }
  if (raw4.length < 0 || raw4.length > 64) {
    return invalid();
  }
  for (let index = 0; index < raw4.length; index += 1) {
    if (!validText(raw4[index], 1, 1024)) {
      return invalid();
    }
  }
  const value4 = Object.freeze([...raw4]);
  Object.defineProperty(values, "features", { enumerable: true, value: value4 });

  if (!Object.hasOwn(input, "port")) {
    missing();
  }
  const raw5 = input["port"];
  if (typeof raw5 !== "number") {
    return invalid();
  }
  if (!Number.isSafeInteger(raw5) || raw5 < 1 || raw5 > 65535) {
    return invalid();
  }
  const value5 = raw5;
  Object.defineProperty(values, "port", { enumerable: true, value: value5 });

  return Object.freeze(values) as Readonly<Configuration>;
};

const generatedProjection = Object.create(null) as Record<string, unknown>;
Object.defineProperty(generatedProjection, "codecAbi", { enumerable: true, value: "astilba.env.codec/v1" });
Object.defineProperty(generatedProjection, "consumer", { enumerable: true, value: "browser" });
Object.defineProperty(generatedProjection, "contract", { enumerable: true, value: "com.astilba.example.pages-router" });
Object.defineProperty(generatedProjection, "decode", { enumerable: true, value: decode });
Object.defineProperty(generatedProjection, "digest", { enumerable: true, value: "sha256-Bbh2AnEyNkoaKnK9ZU7xz0lF5Q-rdi_UdvBaGT0NaZA" });
Object.defineProperty(generatedProjection, "format", { enumerable: true, value: "astilba.env.projection" });
Object.defineProperty(generatedProjection, "formatVersion", { enumerable: true, value: 1 });
Object.defineProperty(generatedProjection, "generated", { enumerable: true, value: "astilba.env.generated-module/v1" });
Object.defineProperty(generatedProjection, "kind", { enumerable: true, value: "public" });
Object.defineProperty(generatedProjection, "lifecycle", { enumerable: true, value: "deployment" });
Object.defineProperty(generatedProjection, "projectionAbi", { enumerable: true, value: "astilba.env.projection/v1" });
export const projection = Object.freeze(generatedProjection) as unknown as BrowserProjection<Configuration>;
