/* Generated by Astilba Env. Do not edit. */
import {
  checkProcessTarget,
  loadProcessTarget,
  type ProcessSource,
  type ProcessTargetDefinition,
} from "@astilba/env/runtime";

export interface Configuration {
  readonly "apiOrigin": string;
  readonly "appName": string;
  readonly "applicationOrigin": string;
  readonly "debug": boolean;
  readonly "features": readonly string[];
  readonly "port": number;
}

const definition = (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "bindings", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "apiOrigin" });
  Object.defineProperty(output, "source", { enumerable: true, value: "API_URL" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "appName" });
  Object.defineProperty(output, "source", { enumerable: true, value: "APP_NAME" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "applicationOrigin" });
  Object.defineProperty(output, "source", { enumerable: true, value: "APPLICATION_ORIGIN" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "debug" });
  Object.defineProperty(output, "source", { enumerable: true, value: "DEBUG" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "features" });
  Object.defineProperty(output, "source", { enumerable: true, value: "FEATURES" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "port" });
  Object.defineProperty(output, "source", { enumerable: true, value: "APPLICATION_PORT" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "generated", { enumerable: true, value: "astilba.env.generated-module/v1" });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "projection", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "canonicalisation", { enumerable: true, value: "astilba.jcs/v1" });
  Object.defineProperty(output, "codecAbi", { enumerable: true, value: "astilba.env.codec/v1" });
  Object.defineProperty(output, "consumer", { enumerable: true, value: "browser" });
  Object.defineProperty(output, "contract", { enumerable: true, value: "com.astilba.example.pages-router" });
  Object.defineProperty(output, "entries", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.origin-ascii/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "origin" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.pages-router","apiOrigin"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "apiOrigin" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.string-code-point/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "string" });
  Object.defineProperty(output, "maxCodePoints", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minCodePoints", { enumerable: true, value: 1 });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.pages-router","appName"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "appName" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.origin-ascii/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "origin" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.pages-router","applicationOrigin"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "applicationOrigin" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.boolean-exact/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "invalid" });
  Object.defineProperty(output, "falseInput", { enumerable: true, value: "false" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "boolean" });
  Object.defineProperty(output, "trueInput", { enumerable: true, value: "true" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.pages-router","debug"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "debug" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.string-list-comma/v1" });
  Object.defineProperty(output, "emptyItems", { enumerable: true, value: "drop" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "string-list" });
  Object.defineProperty(output, "maximumItemCodePoints", { enumerable: true, value: 1024 });
  Object.defineProperty(output, "maximumItems", { enumerable: true, value: 64 });
  Object.defineProperty(output, "minimumItemCodePoints", { enumerable: true, value: 1 });
  Object.defineProperty(output, "minimumItems", { enumerable: true, value: 0 });
  Object.defineProperty(output, "separator", { enumerable: true, value: "," });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.pages-router","features"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "features" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.safe-integer-decimal/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "missing" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "safe-integer" });
  Object.defineProperty(output, "maximum", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minimum", { enumerable: true, value: 1 });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.example.pages-router","port"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "port" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "format", { enumerable: true, value: "astilba.env.projection" });
  Object.defineProperty(output, "formatVersion", { enumerable: true, value: 1 });
  Object.defineProperty(output, "kind", { enumerable: true, value: "public" });
  Object.defineProperty(output, "projectionAbi", { enumerable: true, value: "astilba.env.projection/v1" });
  return Object.freeze(output);
})() });
  return Object.freeze(output);
})() as ProcessTargetDefinition;

export const check = (source: ProcessSource) =>
  checkProcessTarget<Configuration>(definition, source);

export const load = (source: ProcessSource): Configuration =>
  loadProcessTarget<Configuration>(definition, source);
